server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lotte-kokodo/config
          default-label: main
        native:
          search-locations: file://${user.home}/code/lotte-kokodo/config

management:
  endpoints:
    web:
      exposure:
        include: health, busresfresh, beans

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace